config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :pokemons, only: %i[index show]
  root to: 'pokemons#index'

  namespace :api do
    namespace :v1 do
      # resources :pokemons, only: %i[index show], params: :num
      get '/pokemons/', to: 'pokemons#index'
      resources :pokemons, only: [:show], params: :num
    end
  end
end

app/models/ability.rb
class Ability < ApplicationRecord
  has_many :pokemons_abilities
  has_many :pokemons, through: :pokemons_abilities

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokemons_types
  has_many :pokemons_abilities
  has_many :types, through: :pokemons_types
  has_many :abilities, through: :pokemons_abilities

  validates :name, presence: true

  def as_json(*args)
    super.tap { |hash| hash['id'] = hash.delete 'num' }
  end

  def to_param
    num
  end

end

app/models/pokemons_ability.rb
class PokemonsAbility < ApplicationRecord
  belongs_to :pokemon
  belongs_to :ability
end

app/models/pokemons_type.rb
class PokemonsType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pokemons_types
  has_many :pokemons, through: :pokemons_types

  validates :name, presence: true
end

app/controllers/api/v1/pokemons_controller.rb
# frozen_string_literal: true
class Api::V1::PokemonsController < ApplicationController
  def index
    pokemons = Pokemon.includes(:types).select(:id, :name, :num)
    render json: pokemons.to_json(only: %i[num name], include: { types: { only: :name } })
  end

  def show
    pokemon = Pokemon.includes(:types).find_by(num: params[:id])
    render json: pokemon.to_json(include: { types: { only: :name }, abilities: { only: :name } },
                                 except: %i[created_at updated_at] )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemon = Pokemon.page params[:page]
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'POKEDEX' , pokemons_path, :class => 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home' , pokemons_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'JSON index', api_v1_pokemons_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Github', 'https://github.com/Popikadir/pokedex', :class => 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

app/views/pokemons/index.html.erb
<div class="d-flex justify-content-center my-2">
  <%= paginate @pokemon %>
</div>
<div class="container">
  <div class="row col-9 mx-auto">
    <% @pokemon.each do |pokemon| %>
      <div class="card col-3 m-3 hover" style="width: 18rem;">
        <% if pokemon.sprite.present? %>
          <%= image_tag pokemon.sprite , :class => "card-img-top"%>
        <% else %>
          <div class="card-img-top"></div>
        <%end %>
        <div class="card-body">
          <h5 class="card-title text-end"><%= pokemon.name %></h5>
          <p class="card-text text-start">ID: <%= pokemon.num %> </p>
          <p class="card-text text-start">TYPE:
            <% pokemon.types.each do |t| %>
              <%= t.name %>
            <% end %>
          </p>
          <div class="d-flex justify-content-center">
            <%= link_to "voir le pokemon", pokemon_path(pokemon.id), :class => "btn btn-warning mx-auto"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="d-flex justify-content-center my-2">
  <%= paginate @pokemon %>
</div>

app/views/pokemons/show.html.erb
<div class="card mx-auto shadow-lg p-3 mb-5 bg-white rounded" style="width: 30rem;">
  <%= image_tag @pokemon.sprite , :class => "card-img-top"%>
  <div class="card-body">
    <h5 class="card-title text-end"><%= @pokemon.name %></h5>
    <p class="card-text text-start">ID: <%= @pokemon.num %> </p>
    <p class="card-text text-start">TAILLE: <%= @pokemon.height %> dcm</p>
    <p class="card-text text-start">POID: <%= @pokemon.weight %> kg </p>
    <p class="card-text text-start">TYPES:
      <% @pokemon.types.each do |type| %>
        <%= type.name %>
        <% concat('|') if @pokemon.types.last != type %>
      <% end %>
    </p>
    <p class="card-text text-start">ABILITIES:
      <% @pokemon.abilities.each do |ability| %>
        <%= ability.name %>
        <% concat('|') if @pokemon.abilities.last != ability %>
      <% end %>
    <div class="d-flex justify-content-center">
      <%= link_to "revenir au pokedex",:back, :class => "btn btn-warning mx-auto"%>

    </div>
  </div>
</div>